import { Student } from "../types";

export const mockStudents: Student[] = [
  { id: "S01", name: "Aarav Patel", grade: 4 },
  { id: "S02", name: "Vivaan Sharma", grade: 4 },
  { id: "S03", name: "Aditya Singh", grade: 4 },
  { id: "S04", name: "Vihaan Kumar", grade: 4 },
  { id: "S05", name: "Arjun Rao", grade: 4 },
  { id: "S06", name: "Sai Krishna", grade: 4 },
  { id: "S07", name: "Reyansh Gupta", grade: 4 },
  { id: "S08", name: "Krishna Reddy", grade: 4 },
  { id: "S09", name: "Ishaan Desai", grade: 4 },
  { id: "S10", name: "Shaurya Joshi", grade: 4 },
  { id: "S11", name: "Aadhya Menon", grade: 4 },
  { id: "S12", name: "Diya Verma", grade: 4 },
  { id: "S13", name: "Ananya Nair", grade: 4 },
  { id: "S14", name: "Myra Iyer", grade: 4 },
  { id: "S15", name: "Sara Kapoor", grade: 4 },
  { id: "S16", name: "Pari Das", grade: 4 },
  { id: "S17", name: "Avni Bhatt", grade: 4 },
  { id: "S18", name: "Riya Ahuja", grade: 4 },
  { id: "S19", name: "Isha Jain", grade: 4 },
  { id: "S20", name: "Navya Sethi", grade: 4 },
  { id: "S21", name: "Kyra Thakur", grade: 4 },
  { id: "S22", name: "Anvi Chauhan", grade: 4 },
  { id: "S23", name: "Khushi Varma", grade: 4 },
  { id: "S24", name: "Meera D'Souza", grade: 4 },
  { id: "S25", name: "Kiara Pillai", grade: 4 },
];
